version: "3"

services:
  mysql:
    container_name: mariadb
    build: requirements/mariadb
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    restart: always

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    restart: always

  nginx:
    build: requirements/nginx
    ports:
      - "443:443"
    container_name: nginx
    restart: always
