version: '3.8'

services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file: .env
    networks:
      - inception_network
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception_network
    restart: always

  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception_network
    restart: always

networks:
  inception_network:
    driver: bridge

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/cmariot/data/wordpress
      o: bind
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/cmariot/data/mariadb
      o: bind

