version: '3.8'

services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - $HOME/data/mariadb:/var/lib/mysql
    env_file: .env
    networks:
      - inception_network
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - $HOME/data/wordpress:/var/www/wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception_network
    restart: always

  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - $HOME/data/wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception_network
    restart: always

networks:
  inception_network:
    driver: bridge
