version: '3.8'

services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb:inception
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file: .env
    networks:
      - network
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress:inception
    volumes:
      - wordpress_volume:/var/www/wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - network
    restart: on-failure

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx:inception
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - network
    restart: on-failure

networks:
  network:
    driver: bridge

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /Users/cmariot/data/wordpress
      o: bind
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /Users/cmariot/data/mariadb
      o: bind
